In [2]:
import numpy as np

#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [6]:
a = np.arange(12, 24, 1)
# a = np.linspace(12, 24, 12, endpoint = False)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [16]:
a1 = np.reshape(a, (3, 4))
a2 = np.reshape(a, (4, 3))
a3 = np.reshape(a, (2, 6))
a4 = np.reshape(a, (3, 4), order='C')
a5 = np.reshape(a, (2, 6), order='F')
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 14 16 18 20 22]
 [13 15 17 19 21 23]]


#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [17]:
a6 = np.reshape(a, (3, -1))
a7 = np.reshape(a, (4, -1))
a8 = np.reshape(a, (-1, 6))
a9 = np.reshape(a, (-1, 4), order='F')
a10 = np.reshape(a, (2, -1), order='C')
print(a6)
print(a7)
print(a8)
print(a9)
print(a10)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 15 18 21]
 [13 16 19 22]
 [14 17 20 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [19]:
a11 = np.reshape(a, (12, 1))
print(a11)
print("Размерность: ", a11.ndim)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
Размерность:  2


#### Ответ: Массив из одного столбца и 12 строк двумерный, поэтому нельзя назвать его одномерным

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [21]:
b = np.random.randn(3, 4)
b_new = np.reshape(b, (1, -1))
print("Исходный массив: ", b)
print("Размер исходного массива: ", b.size)
print("Получившийся массив: ", b_new)
print("Размер получившегося массива: ", b_new.size)

Исходный массив:  [[-1.1173477   0.78767193  1.60687891 -0.16671725]
 [-2.15895008  0.92862998 -1.27331578 -0.89200005]
 [ 0.57652376 -0.38284313 -0.48948953  0.15201892]]
Размер исходного массива:  12
Получившийся массив:  [[-1.1173477   0.78767193  1.60687891 -0.16671725 -2.15895008  0.92862998
  -1.27331578 -0.89200005  0.57652376 -0.38284313 -0.48948953  0.15201892]]
Размер получившегося массива:  12


#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [23]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [24]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [25]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.concatenate((a, b), axis=0)
print("Двумерный массив из нулей: ", a)
print("Двумерный массив из единиц: ", b)
print("Вертикально соединенные массивы: ", v)
print("Размер получившигося массива: ", v.size)

Двумерный массив из нулей:  [[0. 0.]
 [0. 0.]]
Двумерный массив из единиц:  [[1. 1.]
 [1. 1.]
 [1. 1.]]
Вертикально соединенные массивы:  [[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Размер получившигося массива:  10


#### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [8]:
a = np.arange(12)
A = np.reshape(a, (4, 3))
At = np.transpose(A)
B = A @ At
size_B = B.size
det_B = np.linalg.det(B)
print("Одномерный массив: ", a)
print("Двумерный массив: ", A)
print("Транспонированная матрица: ", At)
print("Произведение матриц: ", B)
print("Размер матрицы B: ", size_B)
print("Определитель матрицы B: ", det_B)

Одномерный массив:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Двумерный массив:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Транспонированная матрица:  [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
Произведение матриц:  [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размер матрицы B:  16
Определитель матрицы B:  0.0


#### Ответ: Размер матрицы B = 16. Вычислить обратную матрицу для B нельзя, т.к. её определитель равен нулю.

#### 10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [28]:
np.random.seed(42)
a = np.random.randint(0, 10, 3)
print(a)

[6 3 7]


#### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [13]:
c = np.random.randint(0, 16, size = 16)
print(c)

[ 6 15  9  4 14  4  6  1 15  7  7  8  2 12  2 15]


#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [15]:
C = np.reshape(c, (4, 4))
print(C)
D = C * 10 + B
print("Новая матрица D: ", D)
det_D = np.linalg.det(D)
rang_D = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print("Определитель матрицы D: ", det_D)
print("Ранг матрицы D: ", rang_D)
print("Обратная матрица для матрицы D: ", D_inv)

[[ 6 15  9  4]
 [14  4  6  1]
 [15  7  7  8]
 [ 2 12  2 15]]
Новая матрица D:  [[ 65 164 113  72]
 [154  90 146 132]
 [173 156 219 292]
 [ 52 242 232 452]]
Определитель матрицы D:  15156000.000000112
Ранг матрицы D:  4
Обратная матрица для матрицы D:  [[ 0.04062813 -0.25937978  0.24892056 -0.09153075]
 [ 0.03915545 -0.19923727  0.18245975 -0.06592505]
 [-0.08174716  0.52214041 -0.48666139  0.17493006]
 [ 0.01632093 -0.13148984  0.12346529 -0.04174848]]


#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [23]:
np.place(D_inv, D_inv < 0, 0)
np.place(D_inv, D_inv > 0, 1)
print(D_inv)
E = np.where(D_inv, B, C)
print(E)

[[1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]
[[  5  15  23   4]
 [ 14   4  86   1]
 [ 15  86   7 212]
 [ 32  12 212  15]]
